### ISSUE TITLE
12-hour clock shows midnight and noon as 00

### ISSUE THREAD

**Issue by probablyethan** [rdnt/m8#15] opened 2023-05-27 20:59 UTC
**Describe the issue**
When set to 12-hour clock, the 0th and 12th hours (midnight and noon) show as "00", instead of "12".

**To Reproduce**
1. Ensure military time override slider is not enabled in m8face settings
2. Go to Settings > System > Date & time
3. Disable slider for Automatic date & time
4. Set time to any minute in midnight or noon
5. Navigate back to watch face
6. Observe that time shows as "00:mm" rather than "12:mm"

**Device info:**
 - WearOS version: 3.5
 - Device model: Google Pixel Watch
 - Device build: RWDA.230114.013
 - m8 version: 2.9.8 (I don't believe this issue was present in previous builds)

**Comment by rdnt** [comment] 2023-05-27 21:36
Hi! Thank you for the report and detailed description. This seems to be a regression, it will be addressed as soon as possible. I'll report back on this issue once a release with the fix has been deployed.

**Comment by rdnt** [comment] 2023-05-31 11:40
Released in production, v2.9.9

**Comment by rdnt** [comment] 2023-06-04 18:49
Reopening as this seems to have introduced an additional bug.

**Comment by rdnt** [comment] 2023-06-22 09:18
Released in v2.11.2 (prod). See [CHANGELOG.md](https://github.com/rdnt/m8/blob/main/CHANGELOG.md) for details.

@probablyethan Thank you for bringing this to my attention. Much appreciated ❤️

**Closed** 2023-06-22 09:18 UTC
Labels: bug, released
